\section{tasks::task\-Error Class Reference}
\label{classtasks_1_1taskError}\index{tasks::taskError@{tasks::taskError}}
\subsection*{Public Member Functions}
\begin{CompactItemize}
\item 
def \textbf{\_\-\_\-init\_\-\_\-}\label{classtasks_1_1taskError_a072222b420274bbfb156e28a39df727}

\item 
def \textbf{\_\-\_\-init\_\-\_\-}\label{classtasks_1_1taskError_a072222b420274bbfb156e28a39df727}

\end{CompactItemize}
\subsection*{Public Attributes}
\begin{CompactItemize}
\item 
\textbf{args}\label{classtasks_1_1taskError_7d6e0cf7a415cd171699f9502995f90d}

\end{CompactItemize}


\subsection{Detailed Description}


\footnotesize\begin{verbatim}Module-specific error, to be raised when an 'expected' exception occurs
   during the processing of a task. This error should then be caught by the
   task manager, avoiding nasty error output.
\end{verbatim}
\normalsize
 



The documentation for this class was generated from the following files:\begin{CompactItemize}
\item 
old/PANICtool-1.0/tasks.py\item 
old/tasks.py\end{CompactItemize}
